-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departamentos
(
    "idDepartamento" integer NOT NULL,
    "nombreDepartamento" character varying(50),
    PRIMARY KEY ("idDepartamento")
);

CREATE TABLE IF NOT EXISTS public.ciudad
(
    "idCiudad" integer NOT NULL,
    "nombreCiudad" character varying(50) NOT NULL,
    "codigoPostal" integer,
    "idDepartamento" integer NOT NULL,
    PRIMARY KEY ("idCiudad")
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    "idCliente" integer NOT NULL,
    "idCiudad" integer NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    email character varying(100),
    celular character varying(20) NOT NULL,
    "fechaNacimiento" date,
    "fechaIngreso" date,
    PRIMARY KEY ("idCliente")
);

CREATE TABLE IF NOT EXISTS public.agendamiento
(
    "idAgendamiento" integer NOT NULL,
    fecha_registro date NOT NULL,
    hora_registro time without time zone NOT NULL,
    fecha_reserva date NOT NULL,
    hora_reserva time without time zone NOT NULL,
    estado character varying(15) NOT NULL,
    "idCliente" integer NOT NULL,
    PRIMARY KEY ("idAgendamiento")
);

ALTER TABLE IF EXISTS public.ciudad
    ADD FOREIGN KEY ("idDepartamento")
    REFERENCES public.departamentos ("idDepartamento") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.clientes
    ADD FOREIGN KEY ("idCiudad")
    REFERENCES public.ciudad ("idCiudad") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.agendamiento
    ADD FOREIGN KEY ("idCliente")
    REFERENCES public.clientes ("idCliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;